CREATE DATABASE antenna;
USE antenna;
CREATE TABLE users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(25) UNIQUE NOT NULL, socket VARCHAR(19) NOT NULL, room VARCHAR(20) NOT NULL, time VARCHAR(13) NOT NULL, stamp INT(8) NOT NULL, moderator INT DEFAULT 0, block INT DEFAULT 0);